services:
  - type: web
    name: aplus-pipeline
    env: node
    plan: starter
    runtime: node
    region: virginia            # ← east for lower latency
    buildCommand: "npm ci"
    startCommand: "node index.js"
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      # ---- REQUIRED (pick one of the DB configs) ----
      - key: DATABASE_URL
        sync: false
      - key: POSTGRES_HOST
        sync: false
      - key: POSTGRES_PORT
        value: "5432"
      - key: POSTGRES_DB
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false

      # ---- REQUIRED (app-level) ----
      - key: PRODUCT_ID
        value: "BTC-USD"

      # ---- PUBLIC base URL for cron convenience ----
      - key: PUBLIC_BASE_URL
        value: "https://aplus-pipeline.onrender.com"   # <-- replace with your actual Render URL after first deploy

      # ---- SECURITY TOKENS ----
      - key: TV_API_KEY
        sync: false
      - key: RETENTION_TOKEN
        sync: false
      - key: BACKUP_TOKEN
        sync: false
      - key: ZAP_API_KEY
        sync: false

      # ---- OPTIONAL INTEGRATIONS ----
      - key: ZAP_B_URL
        sync: false
      - key: ZAP_DOM_URL
        sync: false
      - key: ZAP_DOM_API_KEY
        sync: false
      - key: CRONITOR_URL
        sync: false

      # ---- TUNING ----
      - key: DOM_POLL_MS
        value: "9000"
      - key: CVD_EMA_LEN
        value: "34"
      - key: OFI_EMA_LEN
        value: "34"
      - key: MAX_DOM_AGE_MS
        value: "30000"
      - key: MAX_CVD_AGE_MS
        value: "30000"
      - key: MAX_AGE_MS
        value: "180000"
      - key: COOLDOWN_SEC
        value: "300"
      - key: PRUNE_DAYS
        value: "14"

      # ---- RETENTION WINDOWS ----
      - key: RETENTION_DOM_DAYS
        value: "14"
      - key: RETENTION_CVD_DAYS
        value: "14"
      - key: RETENTION_OFI_DAYS
        value: "14"
      - key: RETENTION_APLUS_DAYS
        value: "180"

      # ---- IMPACT SIZING ----
      - key: IMP_SPREAD_TIGHT_BPS
        value: "1.5"
      - key: IMP_SPREAD_WIDE_BPS
        value: "6"
      - key: IMP_VOL_CALM_BPS
        value: "5"
      - key: IMP_VOL_TURB_BPS
        value: "25"

      # ---- REGIME ENFORCEMENT (optional) ----
      - key: REQUIRE_REGIME_OK
        value: "false"
      - key: REQUIRE_REGIME_FOR_SIDEWAYS_ONLY
        value: "false"
      - key: MIN_REGIME_CONF
        value: ""                 # e.g., "0.5"

      # ---- PORT (Render sets this; keep for local) ----
      - key: PORT
        value: "3000"

cronJobs:
  # 1️⃣ Health ping — every 5 minutes
  - name: aplus-health-ping
    schedule: "*/5 * * * *"
    httpMethod: GET
    url: "https://cronitor-heartbeat-worker.onrender.com/health"

  # 2️⃣ Retention cleanup — daily 05:00 UTC
  - name: aplus-nightly-prune
    schedule: "0 5 * * *"
    httpMethod: GET
    url: "https://cronitor-heartbeat-worker.onrender.com/retention?token=7c13f3aa50db4f3b82afc8a68d29c987"
    headers:
      - key: X-Auth-Token
        value: "7c13f3aa50db4f3b82afc8a68d29c987"

  # 3️⃣ Backup small — gzip dump under 30s
  - name: aplus-backup-small
    schedule: "15 5 * * *"
    httpMethod: GET
    url: "https://cronitor-heartbeat-worker.onrender.com/backup?token=7c13f3aa50db4f3b82afc8a68d29c987&days=1"
    headers:
      - key: X-Auth-Token
        value: "7c13f3aa50db4f3b82afc8a68d29c987"

  # 4️⃣ Backup check — integrity snapshot
  - name: aplus-backup-check
    schedule: "20 5 * * *"
    httpMethod: GET
    url: "https://cronitor-heartbeat-worker.onrender.com/backup/check?token=7c13f3aa50db4f3b82afc8a68d29c987"
    headers:
      - key: X-Auth-Token
        value: "7c13f3aa50db4f3b82afc8a68d29c987"

  # 5️⃣ Integrity self-check — deep pipeline test
  - name: aplus-integrity-selfcheck
    schedule: "25 5 * * *"
    httpMethod: GET
    url: "https://cronitor-heartbeat-worker.onrender.com/internal/integrity"
